// This file contained the EF 6.x code-first migration generated by
// EntityFramework 6.4.4. It has been superseded by EF Core migrations.
//
// To recreate the schema under EF Core, run:
//   dotnet ef migrations add InitialCreate
//   dotnet ef database update
//
// The original migration logic is preserved below as a comment for reference.

/*
namespace WebApplication2.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Initial : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Products",
                c => new
                    {
                        ID = c.Int(nullable: false, identity: true),
                        Name = c.String(maxLength: 60),
                        ExpirationDate = c.DateTime(nullable: false),
                        QRCode = c.String(nullable: false, maxLength: 10),
                        Price = c.Decimal(nullable: false, precision: 18, scale: 2),
                    })
                .PrimaryKey(t => t.ID);
        }
        
        public override void Down()
        {
            DropTable("dbo.Products");
        }
    }
}
*/
