// This file contained the EF 6.x auto-generated migration metadata generated by
// EntityFramework 6.4.4. It has been superseded by EF Core migrations.
//
// To recreate migrations under EF Core, run:
//   dotnet ef migrations add InitialCreate
//   dotnet ef database update
//
// The original metadata is preserved below as a comment for reference.

/*
// <auto-generated />
namespace WebApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial));
        
        string IMigrationMetadata.Id
        {
            get { return "202307041315020_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
*/
